/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gala.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gala.pb-c.h"
void   header__init
                     (Header         *message)
{
  static const Header init_value = HEADER__INIT;
  *message = init_value;
}
size_t header__get_packed_size
                     (const Header *message)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t header__pack
                     (const Header *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t header__pack_to_buffer
                     (const Header *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Header *
       header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Header *)
     protobuf_c_message_unpack (&header__descriptor,
                                allocator, len, data);
}
void   header__free_unpacked
                     (Header *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n1__data__init
                     (N1Data         *message)
{
  static const N1Data init_value = N1__DATA__INIT;
  *message = init_value;
}
size_t n1__data__get_packed_size
                     (const N1Data *message)
{
  assert(message->base.descriptor == &n1__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n1__data__pack
                     (const N1Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n1__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n1__data__pack_to_buffer
                     (const N1Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n1__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N1Data *
       n1__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N1Data *)
     protobuf_c_message_unpack (&n1__data__descriptor,
                                allocator, len, data);
}
void   n1__data__free_unpacked
                     (N1Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n1__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n1__message__init
                     (N1Message         *message)
{
  static const N1Message init_value = N1__MESSAGE__INIT;
  *message = init_value;
}
size_t n1__message__get_packed_size
                     (const N1Message *message)
{
  assert(message->base.descriptor == &n1__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n1__message__pack
                     (const N1Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n1__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n1__message__pack_to_buffer
                     (const N1Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n1__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N1Message *
       n1__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N1Message *)
     protobuf_c_message_unpack (&n1__message__descriptor,
                                allocator, len, data);
}
void   n1__message__free_unpacked
                     (N1Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n1__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n2__data__init
                     (N2Data         *message)
{
  static const N2Data init_value = N2__DATA__INIT;
  *message = init_value;
}
size_t n2__data__get_packed_size
                     (const N2Data *message)
{
  assert(message->base.descriptor == &n2__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n2__data__pack
                     (const N2Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n2__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n2__data__pack_to_buffer
                     (const N2Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n2__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N2Data *
       n2__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N2Data *)
     protobuf_c_message_unpack (&n2__data__descriptor,
                                allocator, len, data);
}
void   n2__data__free_unpacked
                     (N2Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n2__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n2__message__init
                     (N2Message         *message)
{
  static const N2Message init_value = N2__MESSAGE__INIT;
  *message = init_value;
}
size_t n2__message__get_packed_size
                     (const N2Message *message)
{
  assert(message->base.descriptor == &n2__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n2__message__pack
                     (const N2Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n2__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n2__message__pack_to_buffer
                     (const N2Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n2__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N2Message *
       n2__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N2Message *)
     protobuf_c_message_unpack (&n2__message__descriptor,
                                allocator, len, data);
}
void   n2__message__free_unpacked
                     (N2Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n2__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n3__data__init
                     (N3Data         *message)
{
  static const N3Data init_value = N3__DATA__INIT;
  *message = init_value;
}
size_t n3__data__get_packed_size
                     (const N3Data *message)
{
  assert(message->base.descriptor == &n3__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n3__data__pack
                     (const N3Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n3__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n3__data__pack_to_buffer
                     (const N3Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n3__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N3Data *
       n3__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N3Data *)
     protobuf_c_message_unpack (&n3__data__descriptor,
                                allocator, len, data);
}
void   n3__data__free_unpacked
                     (N3Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n3__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n3__message__init
                     (N3Message         *message)
{
  static const N3Message init_value = N3__MESSAGE__INIT;
  *message = init_value;
}
size_t n3__message__get_packed_size
                     (const N3Message *message)
{
  assert(message->base.descriptor == &n3__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n3__message__pack
                     (const N3Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n3__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n3__message__pack_to_buffer
                     (const N3Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n3__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N3Message *
       n3__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N3Message *)
     protobuf_c_message_unpack (&n3__message__descriptor,
                                allocator, len, data);
}
void   n3__message__free_unpacked
                     (N3Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n3__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n4__data__init
                     (N4Data         *message)
{
  static const N4Data init_value = N4__DATA__INIT;
  *message = init_value;
}
size_t n4__data__get_packed_size
                     (const N4Data *message)
{
  assert(message->base.descriptor == &n4__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n4__data__pack
                     (const N4Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n4__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n4__data__pack_to_buffer
                     (const N4Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n4__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N4Data *
       n4__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N4Data *)
     protobuf_c_message_unpack (&n4__data__descriptor,
                                allocator, len, data);
}
void   n4__data__free_unpacked
                     (N4Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n4__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n4__message__init
                     (N4Message         *message)
{
  static const N4Message init_value = N4__MESSAGE__INIT;
  *message = init_value;
}
size_t n4__message__get_packed_size
                     (const N4Message *message)
{
  assert(message->base.descriptor == &n4__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n4__message__pack
                     (const N4Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n4__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n4__message__pack_to_buffer
                     (const N4Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n4__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N4Message *
       n4__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N4Message *)
     protobuf_c_message_unpack (&n4__message__descriptor,
                                allocator, len, data);
}
void   n4__message__free_unpacked
                     (N4Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n4__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n5__data__init
                     (N5Data         *message)
{
  static const N5Data init_value = N5__DATA__INIT;
  *message = init_value;
}
size_t n5__data__get_packed_size
                     (const N5Data *message)
{
  assert(message->base.descriptor == &n5__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n5__data__pack
                     (const N5Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n5__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n5__data__pack_to_buffer
                     (const N5Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n5__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N5Data *
       n5__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N5Data *)
     protobuf_c_message_unpack (&n5__data__descriptor,
                                allocator, len, data);
}
void   n5__data__free_unpacked
                     (N5Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n5__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n5__message__init
                     (N5Message         *message)
{
  static const N5Message init_value = N5__MESSAGE__INIT;
  *message = init_value;
}
size_t n5__message__get_packed_size
                     (const N5Message *message)
{
  assert(message->base.descriptor == &n5__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n5__message__pack
                     (const N5Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n5__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n5__message__pack_to_buffer
                     (const N5Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n5__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N5Message *
       n5__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N5Message *)
     protobuf_c_message_unpack (&n5__message__descriptor,
                                allocator, len, data);
}
void   n5__message__free_unpacked
                     (N5Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n5__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n6__data__init
                     (N6Data         *message)
{
  static const N6Data init_value = N6__DATA__INIT;
  *message = init_value;
}
size_t n6__data__get_packed_size
                     (const N6Data *message)
{
  assert(message->base.descriptor == &n6__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n6__data__pack
                     (const N6Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n6__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n6__data__pack_to_buffer
                     (const N6Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n6__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N6Data *
       n6__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N6Data *)
     protobuf_c_message_unpack (&n6__data__descriptor,
                                allocator, len, data);
}
void   n6__data__free_unpacked
                     (N6Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n6__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n6__message__init
                     (N6Message         *message)
{
  static const N6Message init_value = N6__MESSAGE__INIT;
  *message = init_value;
}
size_t n6__message__get_packed_size
                     (const N6Message *message)
{
  assert(message->base.descriptor == &n6__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n6__message__pack
                     (const N6Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n6__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n6__message__pack_to_buffer
                     (const N6Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n6__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N6Message *
       n6__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N6Message *)
     protobuf_c_message_unpack (&n6__message__descriptor,
                                allocator, len, data);
}
void   n6__message__free_unpacked
                     (N6Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n6__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n7__data__init
                     (N7Data         *message)
{
  static const N7Data init_value = N7__DATA__INIT;
  *message = init_value;
}
size_t n7__data__get_packed_size
                     (const N7Data *message)
{
  assert(message->base.descriptor == &n7__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n7__data__pack
                     (const N7Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n7__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n7__data__pack_to_buffer
                     (const N7Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n7__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N7Data *
       n7__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N7Data *)
     protobuf_c_message_unpack (&n7__data__descriptor,
                                allocator, len, data);
}
void   n7__data__free_unpacked
                     (N7Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n7__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n7__message__init
                     (N7Message         *message)
{
  static const N7Message init_value = N7__MESSAGE__INIT;
  *message = init_value;
}
size_t n7__message__get_packed_size
                     (const N7Message *message)
{
  assert(message->base.descriptor == &n7__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n7__message__pack
                     (const N7Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n7__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n7__message__pack_to_buffer
                     (const N7Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n7__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N7Message *
       n7__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N7Message *)
     protobuf_c_message_unpack (&n7__message__descriptor,
                                allocator, len, data);
}
void   n7__message__free_unpacked
                     (N7Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n7__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n8__data__init
                     (N8Data         *message)
{
  static const N8Data init_value = N8__DATA__INIT;
  *message = init_value;
}
size_t n8__data__get_packed_size
                     (const N8Data *message)
{
  assert(message->base.descriptor == &n8__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n8__data__pack
                     (const N8Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n8__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n8__data__pack_to_buffer
                     (const N8Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n8__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N8Data *
       n8__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N8Data *)
     protobuf_c_message_unpack (&n8__data__descriptor,
                                allocator, len, data);
}
void   n8__data__free_unpacked
                     (N8Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n8__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n8__message__init
                     (N8Message         *message)
{
  static const N8Message init_value = N8__MESSAGE__INIT;
  *message = init_value;
}
size_t n8__message__get_packed_size
                     (const N8Message *message)
{
  assert(message->base.descriptor == &n8__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n8__message__pack
                     (const N8Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n8__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n8__message__pack_to_buffer
                     (const N8Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n8__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N8Message *
       n8__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N8Message *)
     protobuf_c_message_unpack (&n8__message__descriptor,
                                allocator, len, data);
}
void   n8__message__free_unpacked
                     (N8Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n8__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n9__data__init
                     (N9Data         *message)
{
  static const N9Data init_value = N9__DATA__INIT;
  *message = init_value;
}
size_t n9__data__get_packed_size
                     (const N9Data *message)
{
  assert(message->base.descriptor == &n9__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n9__data__pack
                     (const N9Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n9__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n9__data__pack_to_buffer
                     (const N9Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n9__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N9Data *
       n9__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N9Data *)
     protobuf_c_message_unpack (&n9__data__descriptor,
                                allocator, len, data);
}
void   n9__data__free_unpacked
                     (N9Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n9__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n9__message__init
                     (N9Message         *message)
{
  static const N9Message init_value = N9__MESSAGE__INIT;
  *message = init_value;
}
size_t n9__message__get_packed_size
                     (const N9Message *message)
{
  assert(message->base.descriptor == &n9__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n9__message__pack
                     (const N9Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n9__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n9__message__pack_to_buffer
                     (const N9Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n9__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N9Message *
       n9__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N9Message *)
     protobuf_c_message_unpack (&n9__message__descriptor,
                                allocator, len, data);
}
void   n9__message__free_unpacked
                     (N9Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n9__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n10__data__init
                     (N10Data         *message)
{
  static const N10Data init_value = N10__DATA__INIT;
  *message = init_value;
}
size_t n10__data__get_packed_size
                     (const N10Data *message)
{
  assert(message->base.descriptor == &n10__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n10__data__pack
                     (const N10Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n10__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n10__data__pack_to_buffer
                     (const N10Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n10__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N10Data *
       n10__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N10Data *)
     protobuf_c_message_unpack (&n10__data__descriptor,
                                allocator, len, data);
}
void   n10__data__free_unpacked
                     (N10Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n10__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   n10__message__init
                     (N10Message         *message)
{
  static const N10Message init_value = N10__MESSAGE__INIT;
  *message = init_value;
}
size_t n10__message__get_packed_size
                     (const N10Message *message)
{
  assert(message->base.descriptor == &n10__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t n10__message__pack
                     (const N10Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &n10__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t n10__message__pack_to_buffer
                     (const N10Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &n10__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
N10Message *
       n10__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (N10Message *)
     protobuf_c_message_unpack (&n10__message__descriptor,
                                allocator, len, data);
}
void   n10__message__free_unpacked
                     (N10Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &n10__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   node__message__init
                     (NodeMessage         *message)
{
  static const NodeMessage init_value = NODE__MESSAGE__INIT;
  *message = init_value;
}
size_t node__message__get_packed_size
                     (const NodeMessage *message)
{
  assert(message->base.descriptor == &node__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node__message__pack
                     (const NodeMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &node__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node__message__pack_to_buffer
                     (const NodeMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &node__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NodeMessage *
       node__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NodeMessage *)
     protobuf_c_message_unpack (&node__message__descriptor,
                                allocator, len, data);
}
void   node__message__free_unpacked
                     (NodeMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &node__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor header__field_descriptors[5] =
{
  {
    "nodeID",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Header, nodeid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unixTime",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Header, unixtime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fw_version",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Header, fw_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_voltage",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Header, battery_voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet_rolling_num",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Header, packet_rolling_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned header__field_indices_by_name[] = {
  3,   /* field[3] = battery_voltage */
  2,   /* field[2] = fw_version */
  0,   /* field[0] = nodeID */
  4,   /* field[4] = packet_rolling_num */
  1,   /* field[1] = unixTime */
};
static const ProtobufCIntRange header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Header",
  "Header",
  "Header",
  "",
  sizeof(Header),
  5,
  header__field_descriptors,
  header__field_indices_by_name,
  1,  header__number_ranges,
  (ProtobufCMessageInit) header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n1__data__field_descriptors[4] =
{
  {
    "indoor_wb_temperature",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(N1Data, indoor_wb_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_light",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N1Data, indoor_light),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_humidity",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N1Data, indoor_humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_db_temperature",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(N1Data, indoor_db_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n1__data__field_indices_by_name[] = {
  3,   /* field[3] = indoor_db_temperature */
  2,   /* field[2] = indoor_humidity */
  1,   /* field[1] = indoor_light */
  0,   /* field[0] = indoor_wb_temperature */
};
static const ProtobufCIntRange n1__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor n1__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N1_Data",
  "N1Data",
  "N1Data",
  "",
  sizeof(N1Data),
  4,
  n1__data__field_descriptors,
  n1__data__field_indices_by_name,
  1,  n1__data__number_ranges,
  (ProtobufCMessageInit) n1__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n1__message__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N1Message, int_),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N1Message, ext),
    &n1__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n1__message__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange n1__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor n1__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N1_Message",
  "N1Message",
  "N1Message",
  "",
  sizeof(N1Message),
  2,
  n1__message__field_descriptors,
  n1__message__field_indices_by_name,
  1,  n1__message__number_ranges,
  (ProtobufCMessageInit) n1__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n2__data__field_descriptors[7] =
{
  {
    "bma_reset_counter",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N2Data, bma_reset_counter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cow_shock_conunt",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N2Data, cow_shock_conunt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cow_temperature_min",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N2Data, cow_temperature_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cow_temperature_max",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N2Data, cow_temperature_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cow_temperature_ave",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N2Data, cow_temperature_ave),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cow_features_set_0_fx",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(N2Data, n_cow_features_set_0_fx),
    offsetof(N2Data, cow_features_set_0_fx),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "behaviour_classes",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N2Data, behaviour_classes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n2__data__field_indices_by_name[] = {
  6,   /* field[6] = behaviour_classes */
  0,   /* field[0] = bma_reset_counter */
  5,   /* field[5] = cow_features_set_0_fx */
  1,   /* field[1] = cow_shock_conunt */
  4,   /* field[4] = cow_temperature_ave */
  3,   /* field[3] = cow_temperature_max */
  2,   /* field[2] = cow_temperature_min */
};
static const ProtobufCIntRange n2__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor n2__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N2_Data",
  "N2Data",
  "N2Data",
  "",
  sizeof(N2Data),
  7,
  n2__data__field_descriptors,
  n2__data__field_indices_by_name,
  1,  n2__data__number_ranges,
  (ProtobufCMessageInit) n2__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n2__message__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N2Message, int_),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N2Message, ext),
    &n2__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n2__message__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange n2__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor n2__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N2_Message",
  "N2Message",
  "N2Message",
  "",
  sizeof(N2Message),
  2,
  n2__message__field_descriptors,
  n2__message__field_indices_by_name,
  1,  n2__message__number_ranges,
  (ProtobufCMessageInit) n2__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n3__data__field_descriptors[4] =
{
  {
    "drinking_water_volume_cumulated",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N3Data, drinking_water_volume_cumulated),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drinking_water_temperature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(N3Data, drinking_water_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sprinkler_water_volume_cumulated",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N3Data, sprinkler_water_volume_cumulated),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sprinkler_water_temperature",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(N3Data, sprinkler_water_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n3__data__field_indices_by_name[] = {
  1,   /* field[1] = drinking_water_temperature */
  0,   /* field[0] = drinking_water_volume_cumulated */
  3,   /* field[3] = sprinkler_water_temperature */
  2,   /* field[2] = sprinkler_water_volume_cumulated */
};
static const ProtobufCIntRange n3__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor n3__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N3_Data",
  "N3Data",
  "N3Data",
  "",
  sizeof(N3Data),
  4,
  n3__data__field_descriptors,
  n3__data__field_indices_by_name,
  1,  n3__data__number_ranges,
  (ProtobufCMessageInit) n3__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n3__message__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N3Message, int_),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N3Message, ext),
    &n3__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n3__message__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange n3__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor n3__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N3_Message",
  "N3Message",
  "N3Message",
  "",
  sizeof(N3Message),
  2,
  n3__message__field_descriptors,
  n3__message__field_indices_by_name,
  1,  n3__message__number_ranges,
  (ProtobufCMessageInit) n3__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n4__data__field_descriptors[3] =
{
  {
    "litter_conductivity",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N4Data, litter_conductivity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "litter_temperature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(N4Data, litter_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "litter_vwc",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(N4Data, litter_vwc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n4__data__field_indices_by_name[] = {
  0,   /* field[0] = litter_conductivity */
  1,   /* field[1] = litter_temperature */
  2,   /* field[2] = litter_vwc */
};
static const ProtobufCIntRange n4__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor n4__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N4_Data",
  "N4Data",
  "N4Data",
  "",
  sizeof(N4Data),
  3,
  n4__data__field_descriptors,
  n4__data__field_indices_by_name,
  1,  n4__data__number_ranges,
  (ProtobufCMessageInit) n4__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n4__message__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N4Message, int_),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N4Message, ext),
    &n4__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n4__message__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange n4__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor n4__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N4_Message",
  "N4Message",
  "N4Message",
  "",
  sizeof(N4Message),
  2,
  n4__message__field_descriptors,
  n4__message__field_indices_by_name,
  1,  n4__message__number_ranges,
  (ProtobufCMessageInit) n4__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n5__data__field_descriptors[7] =
{
  {
    "sound_level_min",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N5Data, sound_level_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sound_level_max",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N5Data, sound_level_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sound_level_avg",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N5Data, sound_level_avg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nh3_ppm",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N5Data, nh3_ppm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "h2s_ppm",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N5Data, h2s_ppm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "co2_ppm",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N5Data, co2_ppm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ch4_ppm",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N5Data, ch4_ppm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n5__data__field_indices_by_name[] = {
  6,   /* field[6] = ch4_ppm */
  5,   /* field[5] = co2_ppm */
  4,   /* field[4] = h2s_ppm */
  3,   /* field[3] = nh3_ppm */
  2,   /* field[2] = sound_level_avg */
  1,   /* field[1] = sound_level_max */
  0,   /* field[0] = sound_level_min */
};
static const ProtobufCIntRange n5__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor n5__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N5_Data",
  "N5Data",
  "N5Data",
  "",
  sizeof(N5Data),
  7,
  n5__data__field_descriptors,
  n5__data__field_indices_by_name,
  1,  n5__data__number_ranges,
  (ProtobufCMessageInit) n5__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n5__message__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N5Message, int_),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N5Message, ext),
    &n5__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n5__message__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange n5__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor n5__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N5_Message",
  "N5Message",
  "N5Message",
  "",
  sizeof(N5Message),
  2,
  n5__message__field_descriptors,
  n5__message__field_indices_by_name,
  1,  n5__message__number_ranges,
  (ProtobufCMessageInit) n5__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n6__data__field_descriptors[4] =
{
  {
    "indoor_wind_speed_min",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N6Data, indoor_wind_speed_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_wind_speed_max",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N6Data, indoor_wind_speed_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_wind_speed",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N6Data, indoor_wind_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_wind_direction",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N6Data, indoor_wind_direction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n6__data__field_indices_by_name[] = {
  3,   /* field[3] = indoor_wind_direction */
  2,   /* field[2] = indoor_wind_speed */
  1,   /* field[1] = indoor_wind_speed_max */
  0,   /* field[0] = indoor_wind_speed_min */
};
static const ProtobufCIntRange n6__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor n6__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N6_Data",
  "N6Data",
  "N6Data",
  "",
  sizeof(N6Data),
  4,
  n6__data__field_descriptors,
  n6__data__field_indices_by_name,
  1,  n6__data__number_ranges,
  (ProtobufCMessageInit) n6__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n6__message__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N6Message, int_),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N6Message, ext),
    &n6__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n6__message__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange n6__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor n6__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N6_Message",
  "N6Message",
  "N6Message",
  "",
  sizeof(N6Message),
  2,
  n6__message__field_descriptors,
  n6__message__field_indices_by_name,
  1,  n6__message__number_ranges,
  (ProtobufCMessageInit) n6__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n7__data__field_descriptors[1] =
{
  {
    "dry_contact",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(N7Data, dry_contact),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n7__data__field_indices_by_name[] = {
  0,   /* field[0] = dry_contact */
};
static const ProtobufCIntRange n7__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor n7__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N7_Data",
  "N7Data",
  "N7Data",
  "",
  sizeof(N7Data),
  1,
  n7__data__field_descriptors,
  n7__data__field_indices_by_name,
  1,  n7__data__number_ranges,
  (ProtobufCMessageInit) n7__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n7__message__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N7Message, int_),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N7Message, ext),
    &n7__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n7__message__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange n7__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor n7__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N7_Message",
  "N7Message",
  "N7Message",
  "",
  sizeof(N7Message),
  2,
  n7__message__field_descriptors,
  n7__message__field_indices_by_name,
  1,  n7__message__number_ranges,
  (ProtobufCMessageInit) n7__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n8__data__field_descriptors[1] =
{
  {
    "rele",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(N8Data, rele),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n8__data__field_indices_by_name[] = {
  0,   /* field[0] = rele */
};
static const ProtobufCIntRange n8__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor n8__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N8_Data",
  "N8Data",
  "N8Data",
  "",
  sizeof(N8Data),
  1,
  n8__data__field_descriptors,
  n8__data__field_indices_by_name,
  1,  n8__data__number_ranges,
  (ProtobufCMessageInit) n8__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n8__message__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N8Message, int_),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N8Message, ext),
    &n8__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n8__message__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange n8__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor n8__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N8_Message",
  "N8Message",
  "N8Message",
  "",
  sizeof(N8Message),
  2,
  n8__message__field_descriptors,
  n8__message__field_indices_by_name,
  1,  n8__message__number_ranges,
  (ProtobufCMessageInit) n8__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n9__data__field_descriptors[16] =
{
  {
    "case_temperature",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, case_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "case_humidity",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, case_humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_temperature",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, outdoor_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_humidity",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, outdoor_humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_wind_speed_min",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, outdoor_wind_speed_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_wind_speed_max",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, outdoor_wind_speed_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_wind_speed",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, outdoor_wind_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_wind_direction",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, outdoor_wind_direction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_rainfall",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, outdoor_rainfall),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_type",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(N9Data, network_type),
    &network__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signal_strength",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, signal_strength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "solar_voltage",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, solar_voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "solar_current",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, solar_current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latitude",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(N9Data, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(N9Data, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_current",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N9Data, battery_current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n9__data__field_indices_by_name[] = {
  15,   /* field[15] = battery_current */
  1,   /* field[1] = case_humidity */
  0,   /* field[0] = case_temperature */
  13,   /* field[13] = latitude */
  14,   /* field[14] = longitude */
  9,   /* field[9] = network_type */
  3,   /* field[3] = outdoor_humidity */
  8,   /* field[8] = outdoor_rainfall */
  2,   /* field[2] = outdoor_temperature */
  7,   /* field[7] = outdoor_wind_direction */
  6,   /* field[6] = outdoor_wind_speed */
  5,   /* field[5] = outdoor_wind_speed_max */
  4,   /* field[4] = outdoor_wind_speed_min */
  10,   /* field[10] = signal_strength */
  12,   /* field[12] = solar_current */
  11,   /* field[11] = solar_voltage */
};
static const ProtobufCIntRange n9__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor n9__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N9_Data",
  "N9Data",
  "N9Data",
  "",
  sizeof(N9Data),
  16,
  n9__data__field_descriptors,
  n9__data__field_indices_by_name,
  1,  n9__data__number_ranges,
  (ProtobufCMessageInit) n9__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n9__message__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N9Message, int_),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N9Message, ext),
    &n9__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n9__message__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange n9__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor n9__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N9_Message",
  "N9Message",
  "N9Message",
  "",
  sizeof(N9Message),
  2,
  n9__message__field_descriptors,
  n9__message__field_indices_by_name,
  1,  n9__message__number_ranges,
  (ProtobufCMessageInit) n9__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n10__data__field_descriptors[5] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(N10Data, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(N10Data, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "case_temperature",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(N10Data, case_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "case_humidity",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(N10Data, case_humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_insects_count_packed",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(N10Data, n_indoor_insects_count_packed),
    offsetof(N10Data, indoor_insects_count_packed),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n10__data__field_indices_by_name[] = {
  3,   /* field[3] = case_humidity */
  2,   /* field[2] = case_temperature */
  4,   /* field[4] = indoor_insects_count_packed */
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
};
static const ProtobufCIntRange n10__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor n10__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N10_Data",
  "N10Data",
  "N10Data",
  "",
  sizeof(N10Data),
  5,
  n10__data__field_descriptors,
  n10__data__field_indices_by_name,
  1,  n10__data__number_ranges,
  (ProtobufCMessageInit) n10__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor n10__message__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N10Message, int_),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(N10Message, ext),
    &n10__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned n10__message__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange n10__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor n10__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "N10_Message",
  "N10Message",
  "N10Message",
  "",
  sizeof(N10Message),
  2,
  n10__message__field_descriptors,
  n10__message__field_indices_by_name,
  1,  n10__message__number_ranges,
  (ProtobufCMessageInit) n10__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor node__message__field_descriptors[10] =
{
  {
    "n1_message",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NodeMessage, test_oneof_case),
    offsetof(NodeMessage, n1_message),
    &n1__message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n2_message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NodeMessage, test_oneof_case),
    offsetof(NodeMessage, n2_message),
    &n2__message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n3_message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NodeMessage, test_oneof_case),
    offsetof(NodeMessage, n3_message),
    &n3__message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n4_message",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NodeMessage, test_oneof_case),
    offsetof(NodeMessage, n4_message),
    &n4__message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n5_message",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NodeMessage, test_oneof_case),
    offsetof(NodeMessage, n5_message),
    &n5__message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n6_message",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NodeMessage, test_oneof_case),
    offsetof(NodeMessage, n6_message),
    &n6__message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n7_message",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NodeMessage, test_oneof_case),
    offsetof(NodeMessage, n7_message),
    &n7__message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n8_message",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NodeMessage, test_oneof_case),
    offsetof(NodeMessage, n8_message),
    &n8__message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n9_message",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NodeMessage, test_oneof_case),
    offsetof(NodeMessage, n9_message),
    &n9__message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n10_message",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NodeMessage, test_oneof_case),
    offsetof(NodeMessage, n10_message),
    &n10__message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node__message__field_indices_by_name[] = {
  9,   /* field[9] = n10_message */
  0,   /* field[0] = n1_message */
  1,   /* field[1] = n2_message */
  2,   /* field[2] = n3_message */
  3,   /* field[3] = n4_message */
  4,   /* field[4] = n5_message */
  5,   /* field[5] = n6_message */
  6,   /* field[6] = n7_message */
  7,   /* field[7] = n8_message */
  8,   /* field[8] = n9_message */
};
static const ProtobufCIntRange node__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor node__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Node_Message",
  "NodeMessage",
  "NodeMessage",
  "",
  sizeof(NodeMessage),
  10,
  node__message__field_descriptors,
  node__message__field_indices_by_name,
  1,  node__message__number_ranges,
  (ProtobufCMessageInit) node__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue network__enum_values_by_number[3] =
{
  { "GPRS", "NETWORK__GPRS", 0 },
  { "UMTS", "NETWORK__UMTS", 1 },
  { "LTE", "NETWORK__LTE", 2 },
};
static const ProtobufCIntRange network__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex network__enum_values_by_name[3] =
{
  { "GPRS", 0 },
  { "LTE", 2 },
  { "UMTS", 1 },
};
const ProtobufCEnumDescriptor network__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Network",
  "Network",
  "Network",
  "",
  3,
  network__enum_values_by_number,
  3,
  network__enum_values_by_name,
  1,
  network__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
