/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gala.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gala.pb-c.h"
void   node_infos__init
                     (NodeInfos         *message)
{
  static const NodeInfos init_value = NODE_INFOS__INIT;
  *message = init_value;
}
size_t node_infos__get_packed_size
                     (const NodeInfos *message)
{
  assert(message->base.descriptor == &node_infos__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node_infos__pack
                     (const NodeInfos *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &node_infos__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node_infos__pack_to_buffer
                     (const NodeInfos *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &node_infos__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NodeInfos *
       node_infos__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NodeInfos *)
     protobuf_c_message_unpack (&node_infos__descriptor,
                                allocator, len, data);
}
void   node_infos__free_unpacked
                     (NodeInfos *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &node_infos__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_n1__init
                     (DataN1         *message)
{
  static const DataN1 init_value = DATA_N1__INIT;
  *message = init_value;
}
size_t data_n1__get_packed_size
                     (const DataN1 *message)
{
  assert(message->base.descriptor == &data_n1__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_n1__pack
                     (const DataN1 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_n1__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_n1__pack_to_buffer
                     (const DataN1 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_n1__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataN1 *
       data_n1__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataN1 *)
     protobuf_c_message_unpack (&data_n1__descriptor,
                                allocator, len, data);
}
void   data_n1__free_unpacked
                     (DataN1 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_n1__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   payload_n1__init
                     (PayloadN1         *message)
{
  static const PayloadN1 init_value = PAYLOAD_N1__INIT;
  *message = init_value;
}
size_t payload_n1__get_packed_size
                     (const PayloadN1 *message)
{
  assert(message->base.descriptor == &payload_n1__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload_n1__pack
                     (const PayloadN1 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload_n1__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload_n1__pack_to_buffer
                     (const PayloadN1 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload_n1__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PayloadN1 *
       payload_n1__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PayloadN1 *)
     protobuf_c_message_unpack (&payload_n1__descriptor,
                                allocator, len, data);
}
void   payload_n1__free_unpacked
                     (PayloadN1 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload_n1__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_n2__init
                     (DataN2         *message)
{
  static const DataN2 init_value = DATA_N2__INIT;
  *message = init_value;
}
size_t data_n2__get_packed_size
                     (const DataN2 *message)
{
  assert(message->base.descriptor == &data_n2__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_n2__pack
                     (const DataN2 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_n2__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_n2__pack_to_buffer
                     (const DataN2 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_n2__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataN2 *
       data_n2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataN2 *)
     protobuf_c_message_unpack (&data_n2__descriptor,
                                allocator, len, data);
}
void   data_n2__free_unpacked
                     (DataN2 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_n2__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   payload_n2__init
                     (PayloadN2         *message)
{
  static const PayloadN2 init_value = PAYLOAD_N2__INIT;
  *message = init_value;
}
size_t payload_n2__get_packed_size
                     (const PayloadN2 *message)
{
  assert(message->base.descriptor == &payload_n2__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload_n2__pack
                     (const PayloadN2 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload_n2__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload_n2__pack_to_buffer
                     (const PayloadN2 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload_n2__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PayloadN2 *
       payload_n2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PayloadN2 *)
     protobuf_c_message_unpack (&payload_n2__descriptor,
                                allocator, len, data);
}
void   payload_n2__free_unpacked
                     (PayloadN2 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload_n2__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_n3__init
                     (DataN3         *message)
{
  static const DataN3 init_value = DATA_N3__INIT;
  *message = init_value;
}
size_t data_n3__get_packed_size
                     (const DataN3 *message)
{
  assert(message->base.descriptor == &data_n3__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_n3__pack
                     (const DataN3 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_n3__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_n3__pack_to_buffer
                     (const DataN3 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_n3__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataN3 *
       data_n3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataN3 *)
     protobuf_c_message_unpack (&data_n3__descriptor,
                                allocator, len, data);
}
void   data_n3__free_unpacked
                     (DataN3 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_n3__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   payload_n3__init
                     (PayloadN3         *message)
{
  static const PayloadN3 init_value = PAYLOAD_N3__INIT;
  *message = init_value;
}
size_t payload_n3__get_packed_size
                     (const PayloadN3 *message)
{
  assert(message->base.descriptor == &payload_n3__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload_n3__pack
                     (const PayloadN3 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload_n3__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload_n3__pack_to_buffer
                     (const PayloadN3 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload_n3__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PayloadN3 *
       payload_n3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PayloadN3 *)
     protobuf_c_message_unpack (&payload_n3__descriptor,
                                allocator, len, data);
}
void   payload_n3__free_unpacked
                     (PayloadN3 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload_n3__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_n4__init
                     (DataN4         *message)
{
  static const DataN4 init_value = DATA_N4__INIT;
  *message = init_value;
}
size_t data_n4__get_packed_size
                     (const DataN4 *message)
{
  assert(message->base.descriptor == &data_n4__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_n4__pack
                     (const DataN4 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_n4__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_n4__pack_to_buffer
                     (const DataN4 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_n4__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataN4 *
       data_n4__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataN4 *)
     protobuf_c_message_unpack (&data_n4__descriptor,
                                allocator, len, data);
}
void   data_n4__free_unpacked
                     (DataN4 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_n4__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   payload_n4__init
                     (PayloadN4         *message)
{
  static const PayloadN4 init_value = PAYLOAD_N4__INIT;
  *message = init_value;
}
size_t payload_n4__get_packed_size
                     (const PayloadN4 *message)
{
  assert(message->base.descriptor == &payload_n4__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload_n4__pack
                     (const PayloadN4 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload_n4__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload_n4__pack_to_buffer
                     (const PayloadN4 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload_n4__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PayloadN4 *
       payload_n4__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PayloadN4 *)
     protobuf_c_message_unpack (&payload_n4__descriptor,
                                allocator, len, data);
}
void   payload_n4__free_unpacked
                     (PayloadN4 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload_n4__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_n5__init
                     (DataN5         *message)
{
  static const DataN5 init_value = DATA_N5__INIT;
  *message = init_value;
}
size_t data_n5__get_packed_size
                     (const DataN5 *message)
{
  assert(message->base.descriptor == &data_n5__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_n5__pack
                     (const DataN5 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_n5__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_n5__pack_to_buffer
                     (const DataN5 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_n5__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataN5 *
       data_n5__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataN5 *)
     protobuf_c_message_unpack (&data_n5__descriptor,
                                allocator, len, data);
}
void   data_n5__free_unpacked
                     (DataN5 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_n5__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   payload_n5__init
                     (PayloadN5         *message)
{
  static const PayloadN5 init_value = PAYLOAD_N5__INIT;
  *message = init_value;
}
size_t payload_n5__get_packed_size
                     (const PayloadN5 *message)
{
  assert(message->base.descriptor == &payload_n5__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload_n5__pack
                     (const PayloadN5 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload_n5__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload_n5__pack_to_buffer
                     (const PayloadN5 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload_n5__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PayloadN5 *
       payload_n5__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PayloadN5 *)
     protobuf_c_message_unpack (&payload_n5__descriptor,
                                allocator, len, data);
}
void   payload_n5__free_unpacked
                     (PayloadN5 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload_n5__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_n6__init
                     (DataN6         *message)
{
  static const DataN6 init_value = DATA_N6__INIT;
  *message = init_value;
}
size_t data_n6__get_packed_size
                     (const DataN6 *message)
{
  assert(message->base.descriptor == &data_n6__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_n6__pack
                     (const DataN6 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_n6__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_n6__pack_to_buffer
                     (const DataN6 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_n6__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataN6 *
       data_n6__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataN6 *)
     protobuf_c_message_unpack (&data_n6__descriptor,
                                allocator, len, data);
}
void   data_n6__free_unpacked
                     (DataN6 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_n6__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   payload_n6__init
                     (PayloadN6         *message)
{
  static const PayloadN6 init_value = PAYLOAD_N6__INIT;
  *message = init_value;
}
size_t payload_n6__get_packed_size
                     (const PayloadN6 *message)
{
  assert(message->base.descriptor == &payload_n6__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload_n6__pack
                     (const PayloadN6 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload_n6__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload_n6__pack_to_buffer
                     (const PayloadN6 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload_n6__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PayloadN6 *
       payload_n6__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PayloadN6 *)
     protobuf_c_message_unpack (&payload_n6__descriptor,
                                allocator, len, data);
}
void   payload_n6__free_unpacked
                     (PayloadN6 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload_n6__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_n7__init
                     (DataN7         *message)
{
  static const DataN7 init_value = DATA_N7__INIT;
  *message = init_value;
}
size_t data_n7__get_packed_size
                     (const DataN7 *message)
{
  assert(message->base.descriptor == &data_n7__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_n7__pack
                     (const DataN7 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_n7__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_n7__pack_to_buffer
                     (const DataN7 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_n7__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataN7 *
       data_n7__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataN7 *)
     protobuf_c_message_unpack (&data_n7__descriptor,
                                allocator, len, data);
}
void   data_n7__free_unpacked
                     (DataN7 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_n7__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   payload_n7__init
                     (PayloadN7         *message)
{
  static const PayloadN7 init_value = PAYLOAD_N7__INIT;
  *message = init_value;
}
size_t payload_n7__get_packed_size
                     (const PayloadN7 *message)
{
  assert(message->base.descriptor == &payload_n7__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload_n7__pack
                     (const PayloadN7 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload_n7__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload_n7__pack_to_buffer
                     (const PayloadN7 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload_n7__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PayloadN7 *
       payload_n7__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PayloadN7 *)
     protobuf_c_message_unpack (&payload_n7__descriptor,
                                allocator, len, data);
}
void   payload_n7__free_unpacked
                     (PayloadN7 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload_n7__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_n8__init
                     (DataN8         *message)
{
  static const DataN8 init_value = DATA_N8__INIT;
  *message = init_value;
}
size_t data_n8__get_packed_size
                     (const DataN8 *message)
{
  assert(message->base.descriptor == &data_n8__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_n8__pack
                     (const DataN8 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_n8__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_n8__pack_to_buffer
                     (const DataN8 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_n8__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataN8 *
       data_n8__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataN8 *)
     protobuf_c_message_unpack (&data_n8__descriptor,
                                allocator, len, data);
}
void   data_n8__free_unpacked
                     (DataN8 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_n8__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   payload_n8__init
                     (PayloadN8         *message)
{
  static const PayloadN8 init_value = PAYLOAD_N8__INIT;
  *message = init_value;
}
size_t payload_n8__get_packed_size
                     (const PayloadN8 *message)
{
  assert(message->base.descriptor == &payload_n8__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload_n8__pack
                     (const PayloadN8 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload_n8__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload_n8__pack_to_buffer
                     (const PayloadN8 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload_n8__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PayloadN8 *
       payload_n8__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PayloadN8 *)
     protobuf_c_message_unpack (&payload_n8__descriptor,
                                allocator, len, data);
}
void   payload_n8__free_unpacked
                     (PayloadN8 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload_n8__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   status_gateway__init
                     (StatusGateway         *message)
{
  static const StatusGateway init_value = STATUS_GATEWAY__INIT;
  *message = init_value;
}
size_t status_gateway__get_packed_size
                     (const StatusGateway *message)
{
  assert(message->base.descriptor == &status_gateway__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t status_gateway__pack
                     (const StatusGateway *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &status_gateway__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t status_gateway__pack_to_buffer
                     (const StatusGateway *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &status_gateway__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StatusGateway *
       status_gateway__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StatusGateway *)
     protobuf_c_message_unpack (&status_gateway__descriptor,
                                allocator, len, data);
}
void   status_gateway__free_unpacked
                     (StatusGateway *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &status_gateway__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_n9__init
                     (DataN9         *message)
{
  static const DataN9 init_value = DATA_N9__INIT;
  *message = init_value;
}
size_t data_n9__get_packed_size
                     (const DataN9 *message)
{
  assert(message->base.descriptor == &data_n9__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_n9__pack
                     (const DataN9 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_n9__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_n9__pack_to_buffer
                     (const DataN9 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_n9__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataN9 *
       data_n9__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataN9 *)
     protobuf_c_message_unpack (&data_n9__descriptor,
                                allocator, len, data);
}
void   data_n9__free_unpacked
                     (DataN9 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_n9__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   payload_n9__init
                     (PayloadN9         *message)
{
  static const PayloadN9 init_value = PAYLOAD_N9__INIT;
  *message = init_value;
}
size_t payload_n9__get_packed_size
                     (const PayloadN9 *message)
{
  assert(message->base.descriptor == &payload_n9__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload_n9__pack
                     (const PayloadN9 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload_n9__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload_n9__pack_to_buffer
                     (const PayloadN9 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload_n9__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PayloadN9 *
       payload_n9__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PayloadN9 *)
     protobuf_c_message_unpack (&payload_n9__descriptor,
                                allocator, len, data);
}
void   payload_n9__free_unpacked
                     (PayloadN9 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload_n9__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   payload_n10__init
                     (PayloadN10         *message)
{
  static const PayloadN10 init_value = PAYLOAD_N10__INIT;
  *message = init_value;
}
size_t payload_n10__get_packed_size
                     (const PayloadN10 *message)
{
  assert(message->base.descriptor == &payload_n10__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload_n10__pack
                     (const PayloadN10 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload_n10__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload_n10__pack_to_buffer
                     (const PayloadN10 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload_n10__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PayloadN10 *
       payload_n10__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PayloadN10 *)
     protobuf_c_message_unpack (&payload_n10__descriptor,
                                allocator, len, data);
}
void   payload_n10__free_unpacked
                     (PayloadN10 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload_n10__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor node_infos__field_descriptors[5] =
{
  {
    "battery_voltage",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NodeInfos, has_battery_voltage),
    offsetof(NodeInfos, battery_voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fw_version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NodeInfos, has_fw_version),
    offsetof(NodeInfos, fw_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packet_rolling_num",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NodeInfos, has_packet_rolling_num),
    offsetof(NodeInfos, packet_rolling_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodeID",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NodeInfos, has_nodeid),
    offsetof(NodeInfos, nodeid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unixTime",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(NodeInfos, has_unixtime),
    offsetof(NodeInfos, unixtime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node_infos__field_indices_by_name[] = {
  0,   /* field[0] = battery_voltage */
  1,   /* field[1] = fw_version */
  3,   /* field[3] = nodeID */
  2,   /* field[2] = packet_rolling_num */
  4,   /* field[4] = unixTime */
};
static const ProtobufCIntRange node_infos__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor node_infos__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NodeInfos",
  "NodeInfos",
  "NodeInfos",
  "",
  sizeof(NodeInfos),
  5,
  node_infos__field_descriptors,
  node_infos__field_indices_by_name,
  1,  node_infos__number_ranges,
  (ProtobufCMessageInit) node_infos__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_n1__field_descriptors[4] =
{
  {
    "indoor_wb_temperature",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DataN1, has_indoor_wb_temperature),
    offsetof(DataN1, indoor_wb_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_light",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN1, has_indoor_light),
    offsetof(DataN1, indoor_light),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_humidity",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN1, has_indoor_humidity),
    offsetof(DataN1, indoor_humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_db_temperature",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DataN1, has_indoor_db_temperature),
    offsetof(DataN1, indoor_db_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_n1__field_indices_by_name[] = {
  3,   /* field[3] = indoor_db_temperature */
  2,   /* field[2] = indoor_humidity */
  1,   /* field[1] = indoor_light */
  0,   /* field[0] = indoor_wb_temperature */
};
static const ProtobufCIntRange data_n1__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor data_n1__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataN1",
  "DataN1",
  "DataN1",
  "",
  sizeof(DataN1),
  4,
  data_n1__field_descriptors,
  data_n1__field_indices_by_name,
  1,  data_n1__number_ranges,
  (ProtobufCMessageInit) data_n1__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor payload_n1__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN1, int_),
    &node_infos__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN1, ext),
    &data_n1__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload_n1__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange payload_n1__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor payload_n1__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PayloadN1",
  "PayloadN1",
  "PayloadN1",
  "",
  sizeof(PayloadN1),
  2,
  payload_n1__field_descriptors,
  payload_n1__field_indices_by_name,
  1,  payload_n1__number_ranges,
  (ProtobufCMessageInit) payload_n1__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_n2__field_descriptors[7] =
{
  {
    "bma_reset_counter",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN2, has_bma_reset_counter),
    offsetof(DataN2, bma_reset_counter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cow_shock_conunt",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN2, has_cow_shock_conunt),
    offsetof(DataN2, cow_shock_conunt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cow_temperature_min",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN2, has_cow_temperature_min),
    offsetof(DataN2, cow_temperature_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cow_temperature_max",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN2, has_cow_temperature_max),
    offsetof(DataN2, cow_temperature_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cow_temperature_ave",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN2, has_cow_temperature_ave),
    offsetof(DataN2, cow_temperature_ave),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cow_features_set_0_fx",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DataN2, n_cow_features_set_0_fx),
    offsetof(DataN2, cow_features_set_0_fx),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "behaviour_classes",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN2, has_behaviour_classes),
    offsetof(DataN2, behaviour_classes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_n2__field_indices_by_name[] = {
  6,   /* field[6] = behaviour_classes */
  0,   /* field[0] = bma_reset_counter */
  5,   /* field[5] = cow_features_set_0_fx */
  1,   /* field[1] = cow_shock_conunt */
  4,   /* field[4] = cow_temperature_ave */
  3,   /* field[3] = cow_temperature_max */
  2,   /* field[2] = cow_temperature_min */
};
static const ProtobufCIntRange data_n2__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor data_n2__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataN2",
  "DataN2",
  "DataN2",
  "",
  sizeof(DataN2),
  7,
  data_n2__field_descriptors,
  data_n2__field_indices_by_name,
  1,  data_n2__number_ranges,
  (ProtobufCMessageInit) data_n2__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor payload_n2__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN2, int_),
    &node_infos__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN2, ext),
    &data_n2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload_n2__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange payload_n2__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor payload_n2__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PayloadN2",
  "PayloadN2",
  "PayloadN2",
  "",
  sizeof(PayloadN2),
  2,
  payload_n2__field_descriptors,
  payload_n2__field_indices_by_name,
  1,  payload_n2__number_ranges,
  (ProtobufCMessageInit) payload_n2__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_n3__field_descriptors[4] =
{
  {
    "drinking_water_volume_cumulated",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN3, has_drinking_water_volume_cumulated),
    offsetof(DataN3, drinking_water_volume_cumulated),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drinking_water_temperature",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DataN3, has_drinking_water_temperature),
    offsetof(DataN3, drinking_water_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sprinkler_water_volume_cumulated",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN3, has_sprinkler_water_volume_cumulated),
    offsetof(DataN3, sprinkler_water_volume_cumulated),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sprinkler_water_temperature",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DataN3, has_sprinkler_water_temperature),
    offsetof(DataN3, sprinkler_water_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_n3__field_indices_by_name[] = {
  1,   /* field[1] = drinking_water_temperature */
  0,   /* field[0] = drinking_water_volume_cumulated */
  3,   /* field[3] = sprinkler_water_temperature */
  2,   /* field[2] = sprinkler_water_volume_cumulated */
};
static const ProtobufCIntRange data_n3__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor data_n3__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataN3",
  "DataN3",
  "DataN3",
  "",
  sizeof(DataN3),
  4,
  data_n3__field_descriptors,
  data_n3__field_indices_by_name,
  1,  data_n3__number_ranges,
  (ProtobufCMessageInit) data_n3__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor payload_n3__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN3, int_),
    &node_infos__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN3, ext),
    &data_n3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload_n3__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange payload_n3__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor payload_n3__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PayloadN3",
  "PayloadN3",
  "PayloadN3",
  "",
  sizeof(PayloadN3),
  2,
  payload_n3__field_descriptors,
  payload_n3__field_indices_by_name,
  1,  payload_n3__number_ranges,
  (ProtobufCMessageInit) payload_n3__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_n4__field_descriptors[3] =
{
  {
    "litter_conductivity",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN4, has_litter_conductivity),
    offsetof(DataN4, litter_conductivity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "litter_temperature",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DataN4, has_litter_temperature),
    offsetof(DataN4, litter_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "litter_vwc",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DataN4, has_litter_vwc),
    offsetof(DataN4, litter_vwc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_n4__field_indices_by_name[] = {
  0,   /* field[0] = litter_conductivity */
  1,   /* field[1] = litter_temperature */
  2,   /* field[2] = litter_vwc */
};
static const ProtobufCIntRange data_n4__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor data_n4__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataN4",
  "DataN4",
  "DataN4",
  "",
  sizeof(DataN4),
  3,
  data_n4__field_descriptors,
  data_n4__field_indices_by_name,
  1,  data_n4__number_ranges,
  (ProtobufCMessageInit) data_n4__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor payload_n4__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN4, int_),
    &node_infos__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN4, ext),
    &data_n4__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload_n4__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange payload_n4__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor payload_n4__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PayloadN4",
  "PayloadN4",
  "PayloadN4",
  "",
  sizeof(PayloadN4),
  2,
  payload_n4__field_descriptors,
  payload_n4__field_indices_by_name,
  1,  payload_n4__number_ranges,
  (ProtobufCMessageInit) payload_n4__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_n5__field_descriptors[7] =
{
  {
    "sound_level_min",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN5, has_sound_level_min),
    offsetof(DataN5, sound_level_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sound_level_max",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN5, has_sound_level_max),
    offsetof(DataN5, sound_level_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sound_level_avg",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN5, has_sound_level_avg),
    offsetof(DataN5, sound_level_avg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nh3_ppm",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN5, has_nh3_ppm),
    offsetof(DataN5, nh3_ppm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "h2s_ppm",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN5, has_h2s_ppm),
    offsetof(DataN5, h2s_ppm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "co2_ppm",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN5, has_co2_ppm),
    offsetof(DataN5, co2_ppm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ch4_ppm",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN5, has_ch4_ppm),
    offsetof(DataN5, ch4_ppm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_n5__field_indices_by_name[] = {
  6,   /* field[6] = ch4_ppm */
  5,   /* field[5] = co2_ppm */
  4,   /* field[4] = h2s_ppm */
  3,   /* field[3] = nh3_ppm */
  2,   /* field[2] = sound_level_avg */
  1,   /* field[1] = sound_level_max */
  0,   /* field[0] = sound_level_min */
};
static const ProtobufCIntRange data_n5__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor data_n5__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataN5",
  "DataN5",
  "DataN5",
  "",
  sizeof(DataN5),
  7,
  data_n5__field_descriptors,
  data_n5__field_indices_by_name,
  1,  data_n5__number_ranges,
  (ProtobufCMessageInit) data_n5__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor payload_n5__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN5, int_),
    &node_infos__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN5, ext),
    &data_n5__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload_n5__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange payload_n5__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor payload_n5__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "payloadN5",
  "PayloadN5",
  "PayloadN5",
  "",
  sizeof(PayloadN5),
  2,
  payload_n5__field_descriptors,
  payload_n5__field_indices_by_name,
  1,  payload_n5__number_ranges,
  (ProtobufCMessageInit) payload_n5__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_n6__field_descriptors[4] =
{
  {
    "indoor_wind_speed_min",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN6, has_indoor_wind_speed_min),
    offsetof(DataN6, indoor_wind_speed_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_wind_speed_max",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN6, has_indoor_wind_speed_max),
    offsetof(DataN6, indoor_wind_speed_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_wind_speed",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN6, has_indoor_wind_speed),
    offsetof(DataN6, indoor_wind_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_wind_direction",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN6, has_indoor_wind_direction),
    offsetof(DataN6, indoor_wind_direction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_n6__field_indices_by_name[] = {
  3,   /* field[3] = indoor_wind_direction */
  2,   /* field[2] = indoor_wind_speed */
  1,   /* field[1] = indoor_wind_speed_max */
  0,   /* field[0] = indoor_wind_speed_min */
};
static const ProtobufCIntRange data_n6__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor data_n6__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataN6",
  "DataN6",
  "DataN6",
  "",
  sizeof(DataN6),
  4,
  data_n6__field_descriptors,
  data_n6__field_indices_by_name,
  1,  data_n6__number_ranges,
  (ProtobufCMessageInit) data_n6__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor payload_n6__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN6, int_),
    &node_infos__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN6, ext),
    &data_n6__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload_n6__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange payload_n6__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor payload_n6__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PayloadN6",
  "PayloadN6",
  "PayloadN6",
  "",
  sizeof(PayloadN6),
  2,
  payload_n6__field_descriptors,
  payload_n6__field_indices_by_name,
  1,  payload_n6__number_ranges,
  (ProtobufCMessageInit) payload_n6__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_n7__field_descriptors[1] =
{
  {
    "dry_contact",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DataN7, has_dry_contact),
    offsetof(DataN7, dry_contact),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_n7__field_indices_by_name[] = {
  0,   /* field[0] = dry_contact */
};
static const ProtobufCIntRange data_n7__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor data_n7__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataN7",
  "DataN7",
  "DataN7",
  "",
  sizeof(DataN7),
  1,
  data_n7__field_descriptors,
  data_n7__field_indices_by_name,
  1,  data_n7__number_ranges,
  (ProtobufCMessageInit) data_n7__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor payload_n7__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN7, int_),
    &node_infos__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN7, ext),
    &data_n7__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload_n7__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange payload_n7__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor payload_n7__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PayloadN7",
  "PayloadN7",
  "PayloadN7",
  "",
  sizeof(PayloadN7),
  2,
  payload_n7__field_descriptors,
  payload_n7__field_indices_by_name,
  1,  payload_n7__number_ranges,
  (ProtobufCMessageInit) payload_n7__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_n8__field_descriptors[1] =
{
  {
    "rele",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DataN8, has_rele),
    offsetof(DataN8, rele),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_n8__field_indices_by_name[] = {
  0,   /* field[0] = rele */
};
static const ProtobufCIntRange data_n8__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor data_n8__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataN8",
  "DataN8",
  "DataN8",
  "",
  sizeof(DataN8),
  1,
  data_n8__field_descriptors,
  data_n8__field_indices_by_name,
  1,  data_n8__number_ranges,
  (ProtobufCMessageInit) data_n8__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor payload_n8__field_descriptors[2] =
{
  {
    "int",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN8, int_),
    &node_infos__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN8, ext),
    &data_n8__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload_n8__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = int */
};
static const ProtobufCIntRange payload_n8__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor payload_n8__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PayloadN8",
  "PayloadN8",
  "PayloadN8",
  "",
  sizeof(PayloadN8),
  2,
  payload_n8__field_descriptors,
  payload_n8__field_indices_by_name,
  1,  payload_n8__number_ranges,
  (ProtobufCMessageInit) payload_n8__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor status_gateway__field_descriptors[8] =
{
  {
    "battery_voltage",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(StatusGateway, has_battery_voltage),
    offsetof(StatusGateway, battery_voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_current",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(StatusGateway, has_battery_current),
    offsetof(StatusGateway, battery_current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "solar_voltage",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(StatusGateway, has_solar_voltage),
    offsetof(StatusGateway, solar_voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "solar_current",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(StatusGateway, has_solar_current),
    offsetof(StatusGateway, solar_current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_type",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(StatusGateway, has_network_type),
    offsetof(StatusGateway, network_type),
    &network__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signal_strength",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(StatusGateway, has_signal_strength),
    offsetof(StatusGateway, signal_strength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latitude",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(StatusGateway, has_latitude),
    offsetof(StatusGateway, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(StatusGateway, has_longitude),
    offsetof(StatusGateway, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned status_gateway__field_indices_by_name[] = {
  1,   /* field[1] = battery_current */
  0,   /* field[0] = battery_voltage */
  6,   /* field[6] = latitude */
  7,   /* field[7] = longitude */
  4,   /* field[4] = network_type */
  5,   /* field[5] = signal_strength */
  3,   /* field[3] = solar_current */
  2,   /* field[2] = solar_voltage */
};
static const ProtobufCIntRange status_gateway__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor status_gateway__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StatusGateway",
  "StatusGateway",
  "StatusGateway",
  "",
  sizeof(StatusGateway),
  8,
  status_gateway__field_descriptors,
  status_gateway__field_indices_by_name,
  1,  status_gateway__number_ranges,
  (ProtobufCMessageInit) status_gateway__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_n9__field_descriptors[9] =
{
  {
    "case_temperature",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DataN9, has_case_temperature),
    offsetof(DataN9, case_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "case_humidity",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN9, has_case_humidity),
    offsetof(DataN9, case_humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_temperature",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DataN9, has_outdoor_temperature),
    offsetof(DataN9, outdoor_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_humidity",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN9, has_outdoor_humidity),
    offsetof(DataN9, outdoor_humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_wind_speed_min",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN9, has_outdoor_wind_speed_min),
    offsetof(DataN9, outdoor_wind_speed_min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_wind_speed_max",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN9, has_outdoor_wind_speed_max),
    offsetof(DataN9, outdoor_wind_speed_max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_wind_speed",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN9, has_outdoor_wind_speed),
    offsetof(DataN9, outdoor_wind_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_wind_direction",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN9, has_outdoor_wind_direction),
    offsetof(DataN9, outdoor_wind_direction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outdoor_rainfall",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DataN9, has_outdoor_rainfall),
    offsetof(DataN9, outdoor_rainfall),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_n9__field_indices_by_name[] = {
  1,   /* field[1] = case_humidity */
  0,   /* field[0] = case_temperature */
  3,   /* field[3] = outdoor_humidity */
  8,   /* field[8] = outdoor_rainfall */
  2,   /* field[2] = outdoor_temperature */
  7,   /* field[7] = outdoor_wind_direction */
  6,   /* field[6] = outdoor_wind_speed */
  5,   /* field[5] = outdoor_wind_speed_max */
  4,   /* field[4] = outdoor_wind_speed_min */
};
static const ProtobufCIntRange data_n9__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor data_n9__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataN9",
  "DataN9",
  "DataN9",
  "",
  sizeof(DataN9),
  9,
  data_n9__field_descriptors,
  data_n9__field_indices_by_name,
  1,  data_n9__number_ranges,
  (ProtobufCMessageInit) data_n9__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor payload_n9__field_descriptors[2] =
{
  {
    "gwInfo",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN9, gwinfo),
    &status_gateway__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PayloadN9, ext),
    &data_n9__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload_n9__field_indices_by_name[] = {
  1,   /* field[1] = ext */
  0,   /* field[0] = gwInfo */
};
static const ProtobufCIntRange payload_n9__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor payload_n9__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PayloadN9",
  "PayloadN9",
  "PayloadN9",
  "",
  sizeof(PayloadN9),
  2,
  payload_n9__field_descriptors,
  payload_n9__field_indices_by_name,
  1,  payload_n9__number_ranges,
  (ProtobufCMessageInit) payload_n9__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor payload_n10__field_descriptors[5] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(PayloadN10, has_latitude),
    offsetof(PayloadN10, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(PayloadN10, has_longitude),
    offsetof(PayloadN10, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "case_temperature",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(PayloadN10, has_case_temperature),
    offsetof(PayloadN10, case_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "case_humidity",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(PayloadN10, has_case_humidity),
    offsetof(PayloadN10, case_humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indoor_insects_count_packed",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(PayloadN10, n_indoor_insects_count_packed),
    offsetof(PayloadN10, indoor_insects_count_packed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload_n10__field_indices_by_name[] = {
  3,   /* field[3] = case_humidity */
  2,   /* field[2] = case_temperature */
  4,   /* field[4] = indoor_insects_count_packed */
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
};
static const ProtobufCIntRange payload_n10__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor payload_n10__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PayloadN10",
  "PayloadN10",
  "PayloadN10",
  "",
  sizeof(PayloadN10),
  5,
  payload_n10__field_descriptors,
  payload_n10__field_indices_by_name,
  1,  payload_n10__number_ranges,
  (ProtobufCMessageInit) payload_n10__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue network__enum_values_by_number[3] =
{
  { "GPRS", "NETWORK__GPRS", 0 },
  { "UMTS", "NETWORK__UMTS", 1 },
  { "LTE", "NETWORK__LTE", 2 },
};
static const ProtobufCIntRange network__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex network__enum_values_by_name[3] =
{
  { "GPRS", 0 },
  { "LTE", 2 },
  { "UMTS", 1 },
};
const ProtobufCEnumDescriptor network__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Network",
  "Network",
  "Network",
  "",
  3,
  network__enum_values_by_number,
  3,
  network__enum_values_by_name,
  1,
  network__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
